version: '3.1'

services:
  fastapi:
    container_name: ${DOCKER_SERVER_NAME}
    build:
      context: ./fastapi
      dockerfile: dockerfile
    ports:
      - ${DOCKER_SERVER_PORT}:8000
    networks:
      - mynet
    restart: always

  nginx:
    container_name: ${DOCKER_NGINX_NAME}
    build:
        context: ./nginx
        dockerfile: dockerfile
    ports:
        - ${DOCKER_NGINX_PORT}:80
    depends_on:
        - fastapi
    networks:
        - mynet
    environment:
        SERVER_NAME: ${DOCKER_SERVER_NAME}
        SERVER_PORT: 8000
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    restart: always

networks:
  mynet:
