FROM python:3.11.0

ENV PROJECT_PATH /home/fastapi

RUN mkdir -p ${PROJECT_PATH}
WORKDIR ${PROJECT_PATH}
COPY ./requirements.txt ${PROJECT_PATH}
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
COPY . ${PROJECT_PATH}

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]